// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectadvanced.Data;

#nullable disable

namespace projectadvanced.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251202124245_RemoveStripeIdFromPayments")]
    partial class RemoveStripeIdFromPayments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // ... (same as ApplicationDbContextModelSnapshot)
#pragma warning restore 612, 618
        }
    }
}

